### ISSUE TITLE
Checksum

### ISSUE THREAD

**Issue by robro1** [iKoze/3dpct#2]
Hi Florian,
Ich habe nen neuen Fehler, nach einer zufälligen zeit kommt das:
```
~>: ok
<~: N345 G0 F4800 X177.859 Y42.757*118
~>: ok
<~: N346 G1 F2400 X184.259 Y36.358 E17.89773*15
~>: ok
<~: N347 G0 X184.329 Y36.288*26
~>: ok
<~: N348 G0 F4800 X184.259 Y36.923*115
~>: ok
<~: N349 G1 F2400 X178.425 Y42.757 E18.0761*59
~>: ok
<~: N350 G0 X178.355 Y42.827*24
~>: ok
<~: N351 G0 F4800 X178.991 Y42.757*121
~>: ok
<~: N352 G1 F2400 X184.259 Y37.489 E18.23716*12
~>: ok
<~: N353 G0 X184.329 Y37.419*16
~>: Error:checksum mismatch, Last Line: 349
~>: Resend: 350
~>: ok
~>: Error:Line Number is not Last Line Number+1, Last Line: 349
~>: Resend: 350
~>: ok
~>: ok
~>: ok
~>: ok
~>: ok
~>: ok
~>: ok
~>: ok
~>: ok
~>: ok
~>: ok
~>: ok
~>: ok
```

Danke fürs ansehen:)
PS: Ich habs hinbekommen den Code hier richtig zu formatieren:)))))

**Comment by iKoze** [comment]
Hi robro1,

was passiert nach den ganzen oks? Beendet sich das Programm? Bleibt es stehen? Musst du Ctrl+C drücken? Oder kommen einfach bis in alle Unendlichkeit weiter oks? Braucht 3dpct dann 100% cpu Leistung?

Anscheinend kommen Drucker und 3dpct an irgendeinem Punkt außer sync. Da scheinen oks zu kommen, für die davor gar nichts gesendet wurde, was mich extrem verwundert.

Was passiert ist folgendes: nach dem ersten `Resend: 350` versucht 3dpct erst mal alle Nachrichten die kommen, zu flushen. (Zeile 154 self.read_flush()) nach diesem Aufruf scheint es aber nicht weiter zu gehen, da von read_flush theoretisch ein `--- EOF ---` kommen müsste, das erscheint in deiner Ausgabe allerdings nicht.

Viele Grüße,
Florian

**Comment by robro1** [comment]
Hi Florian,
Das Programm bleibt stehen und ich muss ctrl + C drücken. Die Cpu auslastung ist ganz normal.
Gruß Robin

**Comment by iKoze** [comment]
Hi Robin,

das einzige, was Zwischen Ausgabe der oks und dem `--- EOF ---` blocken kann, ist `self.read()`, was wiederrum `result = self.ser.readline().strip()` (Zeile 125) ausführt.

Die [PySerial doku](https://pythonhosted.org/pyserial/shortintro.html#readline) sagt, dass man mit `readline()` vorsichtig sein soll, da es unter Umständen unendlich blockt, wenn man kein Timeout angibt.

Was mich jetzt wundert ist, dass es offensichtlich unendlich blockt. Allerdings habe ich ein Timeout von einer Sekunde angegeben `self.ser = serial.Serial(tty, baud, timeout=1)` (Zeile 100). Das würde auf einen Bug in PySerial deuten.

Bitte bearbeite die `read()`-Funktion wie folgt:

```python
    def read(self):
        print "hello"
        result = self.ser.readline()
        print "bye"
        result = result.strip()
        self.rdm(result)
        return result
```
Und starte einen neuen Druckauftrag. Ist meine Vermutung korrekt, ist die letzte ausgegebene Zeile ein "hello".

Eventuell verursacht eine elektrostatische Entladung an dem Drucker das Problem. Stelle beim drucken immer sicher, dass du dich einmal erdest (z.b. Heizkörper) bevor du den Drucker anfasst, und auch der Drucker korrekt geerdet ist.

Grüße,
Florian

**Comment by robro1** [comment]
Hi Florian,
Nun kommt:
```
Hello
bye
~>: ok

<~: N1 M140 S60*82
Hello
bye
~>: ok

<~: N2 M104 S200*101
Hello
bye
~>: ok

<~: N3 M109 S200*105
Hello
bye
~>:  T:193.2 /200.0 B:57.3 /60.0 @:0 B@:0 W:?

UNKNOWN: T:193.2 /200.0 B:57.3 /60.0 @:0 B@:0 W:?:41
flushing input:
Hello
bye
~>:  T:192.6 /200.0 B:57.3 /60.0 @:0 B@:0 W:?

Hello
bye
~>:  T:192.6 /200.0 B:57.3 /60.0 @:0 B@:127 W:?

Hello
bye
~>:  T:191.6 /200.0 B:57.1 /60.0 @:0 B@:127 W:?

Hello
bye
~>:  T:191.1 /200.0 B:57.1 /60.0 @:21 B@:127 W:?

Hello
bye
~>:  T:190.4 /200.0 B:57.2 /60.0 @:57 B@:127 W:?

Hello
bye
~>:  T:189.5 /200.0 B:57.3 /60.0 @:94 B@:127 W:?

Hello
bye
~>:  T:189.1 /200.0 B:57.5 /60.0 @:116 B@:127 W:?

Hello
bye
~>:  T:188.6 /200.0 B:57.6 /60.0 @:127 B@:127 W:?

Hello
bye
~>:  T:188.6 /200.0 B:57.8 /60.0 @:127 B@:127 W:?

Hello
bye
~>:  T:188.6 /200.0 B:57.9 /60.0 @:127 B@:127 W:?

Hello
bye
~>:  T:189.1 /200.0 B:58.1 /60.0 @:127 B@:127 W:?

Hello
bye
~>:  T:189.5 /200.0 B:58.2 /60.0 @:127 B@:127 W:?

Hello
bye
~>:  T:190.1 /200.0 B:58.4 /60.0 @:124 B@:127 W:?

Hello
bye
~>:  T:191.4 /200.0 B:58.6 /60.0 @:106 B@:127 W:?

Hello
bye
~>:  T:192.5 /200.0 B:58.8 /60.0 @:94 B@:127 W:?

Hello
bye
~>:  T:193.6 /200.0 B:59.0 /60.0 @:81 B@:127 W:?

Hello
bye
~>:  T:194.9 /200.0 B:59.2 /60.0 @:65 B@:127 W:?

Hello
bye
~>:  T:195.9 /200.0 B:59.4 /60.0 @:55 B@:127 W:?

Hello
bye
~>:  T:196.9 /200.0 B:59.5 /60.0 @:44 B@:127 W:?

Hello
bye
~>:  T:198.2 /200.0 B:59.7 /60.0 @:30 B@:127 W:?

Hello
bye
~>:  T:198.9 /200.0 B:59.8 /60.0 @:24 B@:127 W:?

Hello
bye
~>:  T:199.8 /200.0 B:60.0 /60.0 @:16 B@:127 W:5

Hello
bye
~>:  T:200.7 /200.0 B:60.2 /60.0 @:8 B@:127 W:4

Hello
bye
~>:  T:201.4 /200.0 B:60.3 /60.0 @:1 B@:127 W:3

Hello
bye
~>:  T:201.6 /200.0 B:60.5 /60.0 @:7 B@:127 W:2

Hello
bye
~>:  T:202.1 /200.0 B:60.6 /60.0 @:1 B@:127 W:1

Hello
bye
~>:  T:202.1 /200.0 B:60.8 /60.0 @:7 B@:127 W:0

Hello
bye
~>: ok

Hello
```

Gruß Robin

Edit:
Ich habe jetzt .strip wieder activiert. Nun -->
```
~>: ok
<~: N318 G0 F2400 X175.819 Y42.317*114
Hello
bye
~>: ok
<~: N319 G1 F1200 X176.259 Y42.757 E15.16891*2
Hello
bye
~>: ok
<~: N320 G0 F2400 X176.259 Y42.538*127
Hello
bye
~>: ok
<~: N321 M106 S255*101
Hello
bye
~>: ok
<~: N322 G0 F4800 X175.64 Y42.938 Z.31*18
Hello
bye
~>: ok
<~: N323 G1 F2400 X175.64 Y34.138 E15.35915*51
Hello
bye
~>: ok
<~: N324 G1 X184.44 Y34.138 E15.5494*111
Hello
bye
~>: Error:checksum mismatch, Last Line: 319
Hello
bye
~>: Resend: 320
Hello
bye
~>: ok
Hello
bye
~>: ok
Hello
bye
~>: Error:No Line Number with checksum, Last Line: 319
Hello
bye
~>: Error:Line Number is not Last Line Number+1, Last Line: 319
Hello
bye
~>: Resend: 320
Hello
bye
~>: ok
Hello
bye
~>: ok
Hello
bye
~>: ok
Hello
```

EDIT: Ich haben vll. den Fehler behoben (erst ein test Print). Ich habe bei def write(....): ein time.sleep(0.05) eingefügt:)

**Comment by iKoze** [comment]
Mit dem sleep bleibt er nicht mehr hängen? Wie bist du darauf gekommen?

Grüße, Florian

**Comment by robro1** [comment]
Hi Florian
Es hat bisher in 2 Drucken Funktioniert(einer 2h) ich habe den  time sleep auf 0.03 sek runter gesetzt werde den aber noch auf 0.01 sek runter setzen da der das für die kurven so noch nicht schnell genug sendet aber nur. Ich habe mir gedacht vll. sendet der das zu schnell und dann ist der buffer vom board voll oder das board kann nicht mehrere auf einmal verarbeiten oder so und dann einfach ausprobiert:)
Gruß Robin

**Comment by robro1** [comment]
Hi Florian
Es hat bei weiteren drucken mit 0.2 sleep funktioniert bei 0.1 kam ein mal der fehler deswegen habe ich es auf 0.2 gemacht. Aber jetzt habe ich das program mit einem Drucker wo die Repetier Firmware drauf ist ausprobiert und mein problem ist nun das repetier wenn ich den druck abbreche oder der zu ende ist auch von meinen move befehlen ein checksum erwartet also ist meine frage ob ich das checksum deaktivieren kann? :) Bei Marlin ist dies kein problem:)

**Comment by iKoze** [comment]
Hi Robin,

was den Issue mit dem 0.2 angeht, weiß ich noch nicht, wie ich das in die Software integriere. Das mit der Prüfsumme jetzt ist ein neuer Issue. Ich mache einen auf.

**Comment by iKoze** [comment]
Robin, Auf das neue Problem bitte hier antworten: #3

**Comment by robro1** [comment]
Hi Florian,
Das problem lag nur an meiner ...heit SRY das du dafür zeit verschwendet hasst.
Robin
