### ISSUE TITLE
Checksum for move commands

### ISSUE THREAD

**Issue by iKoze** [iKoze/3dpct#3]
> Hi Florian
> Es hat bei weiteren drucken mit 0.2 sleep funktioniert bei 0.1 kam ein mal der fehler deswegen habe ich es auf 0.2 gemacht. Aber jetzt habe ich das program mit einem Drucker wo die Repetier Firmware drauf ist ausprobiert und mein problem ist nun das repetier wenn ich den druck abbreche oder der zu ende ist auch von meinen move befehlen ein checksum erwartet also ist meine frage ob ich das checksum deaktivieren kann? :) Bei Marlin ist dies kein problem:)

**Comment by iKoze** [comment]
Hi Robin,

du brichst den Druck mit Ctrl+C ab und startest dann 3dpcst in dem cli modus? Oder wie genau schickst du die Befehle dann zum Drucker?

Grundsätzlich erwartet der Drucker nach einem Abbruch immer noch die fortlaufende Zeilennummer. Allerdings sollte, sofern du die Prüfsumme bei 3dpct nicht deaktiviert hast, beim neustart von 3dpct der Zeilenzähler vom Drucker zurückgesetzt werden. Hast du eine Fehlermeldung dafür?

Laut [G-Code Wiki](http://reprap.org/wiki/G-code#M110:_Set_Current_Line_Number), wird M110 auch von Repetier unterstützt. Welche Firmware hast du genau?

Grüße,
Florian

**Comment by robro1** [comment]
Hi Florian,

Also ich habe noch ein Control panel in meiner gui wo ich die befehle z.b.: einfach so sende: 
`ser.write (b'M104 S180\r\n')` 

Bei Marlin kann ich das einfach nach einem Druck noch senden oder auch damit beim Drucken die Temperatur ändern das funktioniert auch. Bei Repetier sag der dann checksum error was ja eigentlich auch sinn macht aber ich weiß nicht wie ich nun das Checksum auch mit meinen befehlen senden kann dafür muss ich ja die `self.currentln` haben. die bräuchte ich in einer andren class. Außerdem verstehe ich nicht wie die zahl hinter dem * entsteht. Meine vorerste lösung ist den drucker nach dem Druck/Abrruch neu verbindet, aber somit kann ich im Druck nichts einstellen:(

Gruß Robin

**Comment by iKoze** [comment]
Hi Robin,

jetzt verstehe ich. Du sendest einfach über deine GUI während dem Druck G-Code ohne Prüfsumme an den Drucker. Das ist es in der Tat davon abhängig, was die Firmware daraus macht. Die Marlin-Firmware scheint das locker zu behandeln, da die Befehle ohne Zeilennummer und Prüfsumme gesendet werden, nimmt es diese einfach an.

Ich weiß jetzt nicht, warum du #4 aufgemacht hast, da es ja das selbe Thema ist, aber lass uns in #4 weiter machen, da du den geöffnet hast. Ich schließe hier.

Grüße,
Florian
